alias sinst="sudo apt-get install"
alias act="/home/flo/dev/typesafe-activator/activator-1.3.10-minimal/bin/activator"
alias i3conf="vim ~/.config/i3/conf"
alias ll="ls -lrth"
alias repo="/home/flo/repos/"
