alias sinst="sudo apt-get install"
alias act="/opt/activator/bin/activator"
alias i3conf="vim ~/.config/i3/config"
alias ll="ls -lrth"
alias repo="/home/flo/repos/"
alias beamer="xrandr --addmode DP1-2 1920x1080"
alias nmr="service network-manager restart"
alias xclip="xclip -selection c"
alias envp3a="source activate py3analytics"
alias jce='jupyter console --existing'
alias connect='nmcli c up'
alias disconnect='nmcli c down'
alias connectlist='nmcli d wifi list'
alias xrandr_above='xrandr --output DP1 --auto --above eDP1'
alias xrandr_right='xrandr --output DP1 --auto --right-of eDP1'
alias xrandr_off='xrandr --output DP1 --off'
